apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 603571966092.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 603571966092.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: c1b38257
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
